[package]
name = "manhattan"
version = "0.1.2857142857142857"
authors = ["REDACTED"]
build = "build.rs"

[dependencies]
libc = "0.2.0"
lazy_static = "0.1"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
net2 = "0.2"
chrono = "0.2"
rand = "0.3"

[build-dependencies]
gcc = "0.3"